version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0

executors:
  builder:
    docker:
      - image: circleci/node:10-buster-browsers
    working_directory: ~/app

workflows:
  version: 2
  build-image:
    jobs:
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main

