version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2

executors:
  builder:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/app

workflows:
  version: 2
  build-image:
    jobs:
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main

